sfeed_update: small time format, timeout from 30 to 15 seconds
Signed-off-by: Hiltjo Posthuma <hiltjo@codemadness.org>

diff --git a/sfeed_update b/sfeed_update
--- a/sfeed_update
+++ b/sfeed_update
@@ -44,10 +44,10 @@ merge() {
 # fetch a feed via HTTP/HTTPS etc.
 # fetchfeed(url, name, lastupdated)
 fetchfeed() {
-	if curl -f -s -S -L --max-time 30 -z "$3" "$1"; then
-		printf "[  OK] %s %s\n" "[`date '+%Y-%m-%d %H:%M:%S %Z'`]" "$2" >&2
+	if curl -f -s -S -L --max-time 15 -z "$3" "$1"; then
+		printf "  OK %s %s\n" "`date +'%H:%M:%S'`" "$2" >&2
 	else
-		printf "[FAIL] %s %s\n" "[`date '+%Y-%m-%d %H:%M:%S %Z'`]" "$2" >&2
+		printf "FAIL %s %s\n" "`date +'%H:%M:%S'`" "$2" >&2
 	fi
 }
 
