minor code-style improvements

diff --git a/sfeed_update b/sfeed_update
--- a/sfeed_update
+++ b/sfeed_update
@@ -42,9 +42,9 @@ merge() {
 # fetchfeed(url, name, feedfile)
 fetchfeed() {
 	if curl -f -s -S --max-time 15 -z "$3" "$1"; then
-		printf "  OK %s %s\n" "`date +'%H:%M:%S'`" "$2" >&2
+		printf "  OK %s %s\n" "$(date +'%H:%M:%S')" "$2" >&2
 	else
-		printf "FAIL %s %s\n" "`date +'%H:%M:%S'`" "$2" >&2
+		printf "FAIL %s %s\n" "$(date +'%H:%M:%S')" "$2" >&2
 	fi
 }
 
